blank_issues_enabled: false
contact_links:
  - name: Stackzilla Community Support
    url: https://github.com/Stackzilla/stackzilla/discussions
    about: Please ask and answer questions here.
  - name: Stackzilla Discord
    url: https://discord.gg/CgNUkY3Xyj
    about: Join our Discord community! 
