###############################
# Code coveraeg analysis
###############################
name: Code Coverage Analysis

on:
  workflow_dispatch:
  
jobs:
  cocde_coverage:
    name: Run code coverage 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run the analysis tool
      run: |
        coverage run -m pytest
        coverage xml
        
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
