###############################
# Code coveraeg analysis
###############################
name: Code Coverage Analysis

on:
  workflow_dispatch:

jobs:
  cocde_coverage:
    name: Run code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Run the analysis tool
      run: |
        coverage run -m pytest ./stackzilla/
        coverage xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
